<?php
declare(strict_types=1);
final class ApiTestError extends RuntimeException{function __construct(public string $apiCode){parent::__construct($apiCode);}}
function api_error(string $c,string $m,int $s=400):never{throw new ApiTestError($c);} function api_mysql_datetime(int $t):string{return gmdate('Y-m-d H:i:s',$t);} function api_server_secret():string{return str_repeat('isolated-test-secret-',3);}
require dirname(__DIR__).'/public_html/api/_push_tokens.php';
final class PushPDO extends PDO{public array $calls=[];public bool $tx=false,$committed=false,$rolledBack=false,$failInsert=false,$unchangedMetadata=false,$installationExists=true;function __construct(){}function prepare(string $q,array $o=[]):PDOStatement|false{return new PushStatement($this,$q);}function beginTransaction():bool{$this->tx=true;return true;}function inTransaction():bool{return $this->tx;}function commit():bool{$this->committed=true;$this->tx=false;return true;}function rollBack():bool{$this->rolledBack=true;$this->tx=false;return true;}}
final class PushStatement extends PDOStatement{function __construct(private PushPDO $db,private string $sql){}function execute(?array $p=null):bool{if($this->db->failInsert&&str_starts_with($this->sql,'INSERT'))throw new RuntimeException('insert failed');$this->db->calls[]=[$this->sql,$p];return true;}function rowCount():int{return $this->db->unchangedMetadata?0:1;}function fetchColumn(int $column=0):mixed{return $this->db->installationExists?1:false;}}
function check(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);} function payload(array $c=[]):array{return array_replace(['installation_id'=>'123e4567-e89b-42d3-a456-426614174000','fcm_token'=>str_repeat('safe-token-',8),'app_version'=>'1.0','app_build'=>1,'platform'=>'android','locale'=>'ar-YE','timezone'=>'Asia/Aden','permission_status'=>'Granted'],$c);}
$db=new PushPDO();api_upsert_android_installation($db,42,payload());check($db->committed,'transaction not committed');check(!in_array(payload()['fcm_token'],$db->calls[1][1],true),'raw token leaked');
$meta=new PushPDO();$meta->unchangedMetadata=true;api_upsert_android_installation($meta,42,payload(['fcm_token'=>'','permission_status'=>'Denied']));check(count($meta->calls)===2&&str_starts_with($meta->calls[1][0],'SELECT 1'),'unchanged metadata incorrectly required token');
$failure=new PushPDO();$failure->failInsert=true;try{api_upsert_android_installation($failure,42,payload());throw new RuntimeException('expected failure');}catch(RuntimeException $e){check($failure->rolledBack&&!$failure->committed,'old token disable was not rolled back');}
$detach=new PushPDO();api_disable_android_installation($detach,42,payload(['fcm_token'=>'']));check($detach->calls[0][1][5]===42,'detach not session scoped');
echo "Push installation behavioral tests passed.\n";
